# Generated by Django 3.2 on 2021-09-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_dummy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_link', models.URLField(max_length=50)),
                ('platform', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Solution',
            },
        ),
    ]
